---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-gpu-resource-driver
spec:
  chartRef:
    kind: OCIRepository
    name: intel-gpu-resource-driver
  interval: 1h
  values:
    cdi:
      staticPath: /var/cdi/static
      dynamicPath: /var/cdi/dynamic
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: DaemonSet
              name: intel-gpu-resource-driver-kubelet-plugin
            patch: |
              - op: add
                path: /spec/template/spec/nodeSelector
                value:
                  intel.feature.node.kubernetes.io/gpu: "true"