---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  chartRef:
    kind: OCIRepository
    name: node-feature-discovery
  interval: 1h
  values:
    master:
      resources:
        requests:
          cpu: 23m
          memory: 64M
        limits:
          memory: 64M
    worker:
      config:
        core:
          sources: ["pci", "system", "usb"]
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 300m
          memory: 64M
    gc:
      resources:
        limits:
          cpu: 100m
    prometheus:
      enable: true
