---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: alertmanager-secret
    template:
      data:
        ALERTMANAGER_PUSHOVER_TOKEN: "{{ .ALERTMANAGER_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  data:
    - secretKey: ALERTMANAGER_PUSHOVER_TOKEN
      remoteRef:
        key: dae4d275-7b5c-4a42-86f3-b378012c93d1
    - secretKey: PUSHOVER_USER_KEY
      remoteRef:
        key: ab6a3f60-4a0a-4bcb-abbb-b378012cc806
