---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: truenas-graphite-exporter
spec:
  jobName: graphite-exporter
  staticConfigs:
    - targets: ["truenas.internal:9108"]
  metricsPath: /metrics