---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-release.yaml
  - ./oci-repository.yaml
configMapGenerator:
  - name: graphite-exporter-config
    files:
      - truenas-scale-graphite-mapping.conf=./resources/truenas-scale-graphite-mapping.conf
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled