---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-v18-shared-daily-backup
spec:
  # daily, 1am UCT
  schedule: "0 0 1 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres-v18-shared
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io