---
apiVersion: v1
kind: Service
metadata:
  name: postgres-shared-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "postgres-shared.${PUBLIC_DOMAIN}"
    lbipam.cilium.io/ips: 10.10.16.154
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-v18-shared
    role: primary