---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-secret-test
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        api-token: "{{ .cloudflare-api-token }}"
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: 78ebdf3e-eef9-466e-9774-b37600e4a26c