---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        api-token: "{{ .CLOUDFLARE_API_TOKEN }}"
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: b75763b0-5d96-47a9-ab14-b376016257c6