# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:3oY7xVGlTnN08drUCUZamQoiVT2KofktsF/1fyn/WHRIzSGBFFCkDw==,iv:xmbyahRclSe2Hl90hDg+Qg/BaL0ifUmBFSaUACJ8hRA=,tag:aYJG6ao80qUkN9Nry2zzaQ==,type:str]
sops:
  age:
    - recipient: age1yr8lzheq9nfkyg6ke2yh25ydvm9456p64ukgqu0hxcpvrwyrxy6qgx6luq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NXhFQlEyRm9sZTNRZWwy
        R0xRYktSYi9NcWtpZGE1bmpVbHZLRDlhVm4wCnpyWVZQL3owTlVLRGhmZTl4M1pB
        bFcyNjhvZ24rbWkvcmorSjhDUWxrVVUKLS0tIEJKL2RCb1RKcDI2aGZNSHFMVXYw
        Qi9Da1NxU045dGZQVnc4alRhZDczYWMKBKQISDdWdTykaCWyY+FyOI84lrSL4QKu
        kUvtTrXeu8SMPrdwtkQ/RufKeFZ/88f3Xk/kqj3/8PQFGuGPrL3PeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-06T12:47:35Z"
  mac: ENC[AES256_GCM,data:eyykjFuu6Z4c3eyLTzwXVITCGJjM406+EUvoVmWWm544xrtJdxD/8RNsJnfr3Nl84RsX90wBZkC4/dDdElPV78YmJJa4BGRD0GHXrDCrpMM1Tc65X2sQ6lBse4Yhw6P0bielJsFrBaoipdgLv7NqUz4g+GSudC42Sup2fre1Wvo=,iv:unfL9kxh7vBQTRzfdnI6fJXhlP1OH0sCx4fLKyS/4Uk=,tag:2BhDR13cXbV+WBA2RSKpWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
