# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:me6OjIEtdn64wrZWy5W+T3FsGiGKV5U/VKa06/ZAB5zZsl400oVAiQ==,iv:gc8hqBfHoBNSIaMx+152r3JCenA4tY6hJA/tvBzfLDw=,tag:1dIjWORLZZOxEsdcWVvGVQ==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZDF2Y0RyVGc4TGw5YUlG
        bzlxZmRXT1A1YjFBOFB1RVFYZXp6akpDRkZNClV2c3BKemFUQjNKU2NpTFcyN3NC
        WVNRWk9aemFGdkdCQWpQL0VZWDV0Rk0KLS0tICtyRzNsOGJsT09rb1F1YzNUVC80
        TjluczNTRG9JanNsTFhjU2toNmdrWnMKkU1mh7a37seFmrY3Jopz/UYGqwfZd8Cg
        be1sIezUez0S5U5TpQgsb85w+qv+kLSEmEWkE3opQ0+M2r1lGj+OQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-09T21:43:08Z"
  mac: ENC[AES256_GCM,data:SwUpEKYmg7JwUOSFffWZPvzLf0vCVF1K3xCFGEsc7Q5tpGXBqXF3rfTyzN5ab8UEBDARy3QZo6bPmCtHkAPjrLpYdJXjIjajfq+DTtmNMwUJpt1taGI+ITtOwewmACElxEII+hOV1hkGqEuw8UTl5eEj5HAO7OeIiSjgYMrUvIQ=,iv:KwdSzZ9s4VfPbwyk9XchecIn2vNvoitlQoVcG3F3n3A=,tag:4ArFv59aP3AHVWsGK5Pr2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
