# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:CzL3rablL6Yl8qKIfE6/5adBPG/gborILrsC1tZs8ZLW/8yoWmpb1g==,iv:pabTSUfCCRDYrJgK4T5ysd6ol4Yn6YCYVULrec9Y8Y4=,tag:eBxfRYQD03O9znjHS4gc1Q==,type:str]
sops:
  age:
    - recipient: age1yr8lzheq9nfkyg6ke2yh25ydvm9456p64ukgqu0hxcpvrwyrxy6qgx6luq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqblNscmd5ZmpNK2xVZ1FK
        NDJ1KzRVZnFZbE5DQjMxdXcyT3VkazZrWlFZCm9BVFFDV0JZVFNMTDhXRzRUbFhZ
        MzNUVGQvbXFnYkZ4S1g1TGNlVXVJNHMKLS0tIFQvZGdxaExUZGlRSk8yQ2wvZ2pH
        SjRQNHIvd0wycTVjMFZtZVd6M0JTVGcKtPY03vzjq/RCvNM2tX5HCHIiCdkcqIxy
        loCigSNbGWdwg7kweaFtDM0W9AeI3tchtb9wSIEFXACsS5Qj0hNHnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-07T17:13:55Z"
  mac: ENC[AES256_GCM,data:IBjXb0B6td/sp73EzVbq3vzcVppQthkiKTMXWKlkS7rv3uQkptCiwQxqlqNkhGZqnWw7UVkjGTsi3LeYXnF6p+RT3Y3H9iH3krxdCfTq6ewTUtdqRjPKIyCvDidZ1Fvdo7yTqaOF/+RJCs+uLMlDD+0cwUkBhLJ8Jlmvvck0L54=,iv:KsZxrHgyqo4mEgzQVCqWrRj3OMeqOf1ZOJ1sQvyKjAM=,tag:HWE0IdFXS4vB4EmzZAs82A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
