apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  PUBLIC_DOMAIN: ENC[AES256_GCM,data:8KOi4ANhrNP3x/0=,iv:qJ7VGwBKaHzsEzOQCFksoW+u0JZig2upJ391RFvls0A=,tag:QZBxPTYvoBmdvpcGqYyu2w==,type:str]
  BITWARDEN_PROJECT_ID: ENC[AES256_GCM,data:+L9N9cMyRlMaw//2G2F/LcuXhpXFjybR96LdGlkVCWqrjaZwH43Dj191+Z4kyX2Rrzfl1PrWdnBHhDxi1s0cCt/pg/ZXShA1JIC0OkJqGeY+ZiOICDxEP7T444tbt8MPzdAxd5+wagADd/oL0Su3JnAOOpvdAV+YEpIIw/vA8QYRuiD0fu5su5ZrHbg+VvNlnl8flUyB/mE=,iv:NOib1EHpZfsRH5UxVwXzCH8jIZSyi00ZCKZsEVqQ7rw=,tag:nZzL35U+s85KGt/qHqzeoQ==,type:str]
  BITWARDEN_ORGANIZATION_ID: ENC[AES256_GCM,data:JKc9BI45QWzXx3r0pWaI3LRYLGN339HP1bZBQtoOTBkbrY10,iv:6RIqa1oBN09HLjC3a79KXmxnG5E2/UU/QFGVIclOXrE=,tag:arrgt9JmT9eCFXS3EdGVgg==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMTVmdTkvbFRGdmczV3ZX
        MW9CY0ljQkhNaDhqV1llWHBqQ3M1N3lkOHhrClRVbUN6T3kvRU94MXNrSkUzc29x
        M0MxbHBhS25yYUphdlhvK0ZyOHVHNVkKLS0tIDY0b3JOa2lIZUZVeGRBZWVyZmFj
        a2s4am5xNml0UlFXQUFIeG1GNUcwZEEKSJQayRQFS1/c19v5XCWKJMToqYep/1XN
        nF5ZzsNIROOnpodlTMrEqgQEuHkSYx3CiFsTrWlBGul60ZxZ+uTSeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-14T21:18:29Z"
  mac: ENC[AES256_GCM,data:qSAbDlE7MqzyAIO4AmcR3ZhYb7O2rXTb7FXLCISZ39Bad1z3LfpN0qbKLmuAi+EphGXE6fs5pEE9RFYPAYsW3Ppzbf3JRALLEi7itpoXxiv++2EMoRJOukTV6o0sP8zK1tOZjK5if3a8Y4P7VCxkowvm0oYxESBFxNpHeu/vSa0=,iv:83/R6pU6yybEZMN3mUw+n1kKT1oplpVPnk6ltpA92vA=,tag:aDCyV+1FMgzpk6pIb55DXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
