# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:zmGerP4lDdAxbUWB54K8OGepIEx8SMRjGYipfJZyNFc=,iv:85okwC9TcvOzyP9NwrOyt8ZS5aIfy9X0hGbroJWS2wU=,tag:aJbRxbaEpgBScaNF17/afw==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SGtycEduNkI1bjVIaEdP
        RXNSVHpOQkZ2eFh1T0VtRWtzVXJMSjFGam1FCkQ4L0RrcW00NXBWeW1GNnlNK0Qw
        YmlDaXZKWWNUVXRkVjFTbThlTnlXUVkKLS0tIFVnRU9MbzBJbGZpMUVFV3gwWFJW
        NlZVcFMrVkprSkFKSmpqQ2t1RjY4djgKM2c/ezfydQu2SlvFyQ2PuBzRdxQlj7jb
        n6WPhYpLKRCnHPU0pGaWcgrg+R8RsstKa865NRl4ObxS9EizuekrVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-09T19:19:16Z"
  mac: ENC[AES256_GCM,data:sv8R/No2Qg2zW2QfS3GO3GzhbNYDBoeRcxU09EO3dX77+oHrc9ezV6DuHIncr2yMlGOUVEP8oIcFvBxo8fFzAJvVwUMRdU+19WofNIL4QO2jxU/HxHAphXSuhmQSIc881QPmAu7i3biHKj6E/juOyD+yTmiDd/w4289TWWRdIjM=,iv:S5I/Z7Wzwww66Ovbr7raOJCx4zxFdVaoPdbOIwRTm/E=,tag:F/ZCAV+UeZUnWRdsDz9NXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
