apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:GxFx8YO84j/9gAjFY1a7wsC0yjWhLgsdXb1hLe19+RI=,iv:qHRa7A5Fb9MuwMtc6dKmCPwBPuowiIcxmnJp0NKVvhQ=,tag:9IDm3tOHVONfpj9IbuyW9g==,type:str]
sops:
  age:
    - recipient: age16thtrzvf27zxxg2fa0h0plrjatf9g9v4v80k4h6ntpjaznzkkccqpwdavq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPejlTYUJaOFUxZndPd1dR
        RTNjL0g3bTVtTW9Udmk4dlh1dHpjKzR2NTFnCkpGZzJ6Ni92Z05uRnhYdkVJdThL
        NjZIdUVIU091WnUzYmdnUU9BbFZIOFUKLS0tIDU1U09acE16RCtBL0xUdXU0TzhF
        cFRJLzc3VjB5Z3RyZGpUczVZcnZHYzAKEIfgSdkU8hx55C+ge3EvNp+wHa01MMmL
        Uatdfkz8/54781ToL8C3ZtTmZ3p0NqKZjKcodY62hdmshUOBidnLRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-29T18:44:17Z"
  mac: ENC[AES256_GCM,data:2buLR77ZS+S1wVwgRCKEvD11JhtA38bsRW1Kbexqu/yo2HsJrqp0HYdtu9OQfSXa+rm0m4+mtpkv5kqYTtIhnG0fw5kU/Ul7PgHskzZTiRUrNAJlpGOYxqbSI8DqQQk3od8Z8yjQLDlMCtlHv3IWLNq4bhMVd8Jv7zZCyzYVU2c=,iv:gj/VMzRHGzxhwzbbOFeiMYBaIaOSRyfRnIgweYPSttA=,tag:ivdv1pSQRz/gRbt1cJAqqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
