# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:TuZad5S3d1y0p4wRxT+BzBhrBO02d+yzx1/vUFmBL04=,iv:F5Ag5tqd2GeBZ8Eu/0jNw9uaWXViq8vglcSJ0bjdwmc=,tag:wXv1JunyG42DgD+eIHZGMQ==,type:str]
sops:
  age:
    - recipient: age1yr8lzheq9nfkyg6ke2yh25ydvm9456p64ukgqu0hxcpvrwyrxy6qgx6luq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OUJYMHFSYWlSa1NWS0h6
        Q1NJYTQ2a1pFU1M0Z1RpSEc0UDVsdEtZY2hBCktzZVF1L2pqV3Q1SDJ6cml0cUQ0
        NERHWUduTU5teUhWcHVOUzdCT0g5bzAKLS0tIHRjeTlzVEpIS3ZFdTNSWGZVYmFL
        Mms3bW1QUU1JYkhORHVIeW5rRnRVREkKRafDkndndbcerBG7HwtbMWAolc/Mbrmj
        anS8nLNt5XeUSPCaySX3snuBcJrgsdSBh2EZkLm/4bAbMp3zXp3UZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-06T12:47:35Z"
  mac: ENC[AES256_GCM,data:bJUIUza3uG0sXK54gtfk420aU2X2ldNyYT6V1go8ykJNlxRCCRaasyf487KDhK9CUmjeVBS8untrP2F0GCp7kVrIbur3hJ26ab/bBCWcqwETVMZJqxcqwLs8UNprVgMKz6c4k0fNewrP4uRItoDBJ8bEteErKQKgxG8h/M4zsi8=,iv:d1FH8dtOd8suHDCrYMI5xE87aNG7SxyXCGC0wW5uvMg=,tag:Zu8HAFFMOYWPngInuPkXKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
