# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:bKsoKwVQhb6dgAl2Ugx+v/A2KlNks0nJM0buYKa2XP8=,iv:r5ymHzAw4kzN9Tdfhm8Rl56ni548Lmk9Zf/zAF2/LTo=,tag:7e/SFaO0T17kzwwEP51QJw==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYkp1MmtZaFZNSTZXVlVl
        M2I0ejN5cVAzOEprN1N2bjF5am1pT1VEeW0wClRtTkV6MG04WXV1akU4dXFycEdz
        d1Z0V2Fad1NLTCtvWDBrcUxwNWFZR3MKLS0tIEdCcTI0blhNTHFDdjRkbDd4cEpG
        UXJ4VUZsYWkxV3NjNytGZTUyc1pxdk0KT/pV+3fUHCJVSPlZrFvApkyz9WsAaDQR
        lxQBu5wPhPU5Ly5cG4l4nr7d7mQZikjTZkDf6Rhe/MjyioVRju0VlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-09T21:43:08Z"
  mac: ENC[AES256_GCM,data:J8HwPErT2iAfWl16/45SKXmHcuvhxZayKwCUbGapDQ1Kg1ZZgk8ETumfqpaA43SMIGStTxDaVzGxigj3RtDH20LtC5rARJPTxBpJbETQ4G9hvXXE0Isy3DmX6wesQONHGahRuHUKxglF6L+FlIBdImB3CcqnV68YfVMDs6JXR5g=,iv:tnuOH6vNzGP+bIICKT33C2sY7BRwhz69y4Cr2ahfL5E=,tag:rqRrgIgyISOPPbYM/apHJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
