---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: grafana-admin-secret
    template:
      type: Opaque
      data:
        admin-user: "grafana"
        admin-password: "{{ .GRAFANA_ADMIN_PASSWORD }}"
  data:
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: 90892e6f-0264-44da-a844-b3780154d71f