# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:RbFIB421ozIudAkcAYHLX9tTkR/DRMPkN7sd2prlUhvIdjnCEWk4xA==,iv:6mYPHaaC16SwicnAXuVYdHWnzSiZdVerVSvDyaBCwB8=,tag:e9+KwowLXWLViul1ZeAq3g==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a0ttWitSNGg5K3pkRlps
        bE5nT3dZODdvcVVZa01WWWlQZ0M2WDZzUEFrClpaUVlmUTRPMEFnU3dmZlhiTnov
        bytReHNiVGl6YmtWOVNUaGxuZW9yVG8KLS0tIGE2bjdpekNNa2JpRGxMQkdqMWF6
        MHhrRW5nK3g5ZEZFY0RJK2FUMzRyMXMKCKPMeGotRCJSVRGApad7LVgY/rgDrCdH
        gsyjiYZT0g4U4RUgKxTo/930Krw00B0ozTLVFt0PcrVm7hVg8HlUag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-09T21:43:08Z"
  mac: ENC[AES256_GCM,data:U1W8VI44PpdNckMPPRhj6MNN+X1fDnC6u6YSUT9gJO0FfL/W1UXr//Gal3XqlHFE1wMbJaUB3RWKu/KGI9voQNutZ0k+V6YyKBK4rhWsUrV/yflDvXXf4Ma5uYgLA7it+ew/i6x+AYI7SkvRUpJkMkVEiRY5r1VUdR2Zs0mwz4o=,iv:gB/Hr5E+sJLRtcAhmc0Ul8//8xSsN3MhdkjgGmULil8=,tag:mweicg7gGayIboRe4soiHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
