---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio
spec:
  configuration:
    data:
      compression: bzip2
    destinationPath: s3://cloudnative-pg-shared/
    endpointURL: https://s3.${PUBLIC_DOMAIN}
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cloudnative-pg-secret
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: bzip2
  retentionPolicy: 30d