---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml

  - ./atuin/ks.yaml
  - ./external-services/ks.yaml
  - ./plex/ks.yaml