---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-secret-test
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        CLOUDFLARE_TUNNEL_TOKEN: "{{ .CLOUDFLARE_TUNNEL_TOKEN }}"
  data:
    - secretKey: CLOUDFLARE_TUNNEL_TOKEN
      remoteRef:
        key: 3ad46d0d-4c15-43c8-8c38-b3760160dceb