---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-secret-test
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        TUNNEL_TOKEN: "{{ .CLOUDFLARE_TUNNEL_SECRET }}"
  data:
    - secretKey: CLOUDFLARE_TUNNEL_SECRET
      remoteRef:
        key: 9e0dcf58-8a89-420d-b7bc-b37600edc685