# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:COiXKVx0eukPBpqCiZsOUgDuNK9aInWoXP+rUSf4HD1o36YSIVl0y7Fi7FNBw+cAcDwTj7vzpPJfaXgzQLukZbvXWH2aIEfBbrm2CENmCmu1b7ohYwS2zKPHM0oTiIhQaOy+7No037RpGSSGmzdj77pivjPqdWgho8GwT7PDsTJI6lpJiwp2H5jcSZ5LtEw+6trRxYYNRLltEVBq1zd2epHhoD+Hj517rHSQHXEyD6+VxgC9,iv:mJl+7zAX2JPOrGUAYwwgGpg/Wor1121Mrj2HCSi9KNM=,tag:yRnceFnR9pOivYrgljeBYw==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VGFiNDJrUDBTc0ZaY0Rw
        K0FWZCsrM3FWUy9oNkdSSXVWUTRMNDJ2YmprCno1cmVKbFBUcVYzUHZyY2hjQ0lK
        eXdCUHZUeWQwVG1KSWYxQnZPenZnYUEKLS0tIGdOcVpkbzIyajA4b3dwSzFrd2da
        MEUrdXdSTDkvVlg2ZjZTaVFhZmxtWWcKeKQ5etYj7h1Tt/FA3+l5WAfUpDYPFB5e
        XFOr6/A1SxA8Rzjs+HG+zFc2e97uJcxizt8SEP9rJ1KdovexODvCag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-09T15:03:04Z"
  mac: ENC[AES256_GCM,data:VyTDg091OwdZicWovdTD3/ZwOxCRQst8UOaf9j9rFOFzJ2zSOdINf9rEZLEhLgLr5QNFUbk32u7TYHkA7SO1yzt5+3FtM2dsq6AYefBl6ockk4k3mLgDQXKFn+HsberYwi6R0ZRaAwXqtI++XMvJNhIoJ1fF8XFy5M4G1G1q3nk=,iv:iT3nw463bi88L85QZmdz1rybzv4O3RTbos2qti3bAIo=,tag:JjA1gD7vCDEwZf729t8fDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
