# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:uBnda9IlVO2xM9XEVmrm0PV6PSGW06w3PvPSvLiJIJ2Egazp/Nmvz3OlyYmcXspMy/2y7nVaKjwWtX3QU45Dp7vCexSbM0Pfh0qyHZvIbqtH3U9/l+jjV8xnMDHTKGIYd0g0lAU/D592/Oqi4gz3C8amYr/mvLKD5q459av7yNGciZM7Xbexq+QxGmrkaYf1bvqbCypxEt0TWZ6Mf2gMI/OMW2O/as2Ino67TsiOmxU42kZo,iv:kVDAUwvfAnmHIky2GwuYYkSIbiZs71K1NQabZqQjZhM=,tag:sFiJ9+DWZ7rxpQdeY8IGvQ==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SWl4SWt1dFUzc2oxaWM5
        NVRjVmFNYlhDVFRTekxCd2E4RWtDOWtXaVhnCldBVWc1NHMxQTBxTUVCK082VDJO
        eVV4aUhnR0NBeWlCazN3MUFibEEvOXcKLS0tIGpIM3FrVTV6clBCb2lNdW9JREF2
        a1dUZmxGQ3JMSFVaWDl5ZzFwT2lkRkUKETnW9ciWJ0b1FAS72IVeE8BLpVHBrYqR
        YQQiC29HVJcuKNlT9EoI0Nv59GfKX3IGtl7vKAuUP00E2NTFBBf7Mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-09T21:43:09Z"
  mac: ENC[AES256_GCM,data:TV5Oyqc/RtwMzW4diKIcvRFE1Chwsk4Wnt2AwwHaKM2C/KiYqD87kkov51H+tIsm3+VWUls5qzLiM/GPy39iPT6LIE8BithTSJKOUaOOB4Swgape3txSk1fJwi2RN56V2V+I59fB9AeiK9bQrFonyYtsED/45TazXDbieXE0Mbg=,iv:cs3wJ9QJflXE/QBgEE+queRA8xYjUyetoq/4aYInslo=,tag:uaraLJ92g+5+ZgHlU9CFyA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
