# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Jx/edV+Wg5qpj6NyvXOyA88Z5JvDllgqN+eXqTPiWY8nkmKqCLHhq1y/U3vIVhgHcgrkkgFQ0PgZf339RF5UJEPHklCjMoCPv0zw1KlMOLwXmaVoMEV8/amlaq3tsiXPzarJOoDhGX8vo/DK8+c/5LtLkmPi14tUVjbXS2jWa3L5djVcWWv3bu0+s/xKiVGj62eMVbwGNSR0xztqZP4h8XCH+NlowOuXP0BIdbY9freL92xJ,iv:7g6V0y/4OF1wUSXzlpavFQoMpdlnzbYiWMO81/ve8ro=,tag:27FmfW5goATCpoTUGR8p1Q==,type:str]
sops:
  age:
    - recipient: age1yr8lzheq9nfkyg6ke2yh25ydvm9456p64ukgqu0hxcpvrwyrxy6qgx6luq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweXhGRGw2TDdDakpBZHdP
        blB5bXBUU1RXREdra2RLbUVrK1hKMWlUMDJrCjd1Vkt5Y05URW05VUNxZDg0ZWVl
        U3haaU1LR0Ywd0J6NTM0bFRCR09qQzgKLS0tIFE3dyswV3ZrcDhnS0ZwNWFxVlRO
        ZEZVS1JCbFZJUGFRdXQ4YVMwanpTK0EKG74jhwrP8KNnWBhd0x59cmaPFk7Uun/R
        wWGVQ4CWb7ZJt3qqadNH/8JtML4dEtpIyoFYgxJkn/8V81lEuu8VJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-06T12:47:35Z"
  mac: ENC[AES256_GCM,data:Yf5R4iwUK/fHjmNZMQSIh/Um5g+h6sEJ1fKMFdz25z5VerxAuIyv05ro9/9397iKIY4ZOQ0ATh1rNHwp9QsThwlCanWeyt8oL4YKkGjIktbhw9djrDbgqpOZhR96VJN4Bc/8uF8BFmfEEKWl7pGsYViIy866bq+xsxpOK5kI2jk=,iv:i+GzpzYp0HiHv2xk1T/DdXitDYdn6wPCuqetIW9v3Y4=,tag:14K5RfC1tQoxb3pzFT0KYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
