---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: drawio
spec:
  chartRef:
    kind: OCIRepository
    name: drawio
  interval: 1h
  dependsOn:
    - name: cloudflare-tunnel
      namespace: network
  values:
    controllers:
      drawio:
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"
          configmap.reloader.stakater.com/reload-resources: &configuration drawio-configuration

        containers:
          app:
            image:
              repository: jgraph/drawio
              tag: 28.2.8@sha256:376e32784cdb49c8bd566599646a9931cd455a5542198282414239eae2bc69ef
            env:
              TZ: "America/Chicago"
              DRAWIO_CONFIG:
                valueFrom:
                  configMapKeyRef:
                    name: *configuration
                    key: configuration.json
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              runAsNonRoot: true
              # tomcat user
              runAsUser: 1001
              runAsGroup: 999
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 200m
              limits:
                memory: 512Mi

    defaultPodOptions:
      securityContext:
          fsGroup: 999
          fsGroupChangePolicy: OnRootMismatch
          seccompProfile: { type: RuntimeDefault }

    service:
      app:
        ports:
          http:
            port: &port 80
            targetPort: 8080

    serviceMonitor:
      app:
        endpoints:
          - port: http

    route:
      app:
        annotations:
          # Homepage Automatic Service Discovery
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "draw.io"
          gethomepage.dev/description: "diagramming application"
          gethomepage.dev/icon: "sh-draw-io"
          gethomepage.dev/group: "Documentation"
        hostnames: ["{{ .Release.Name }}.${PUBLIC_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port