{
 "title": "APC Smart-UPS SRT-5000",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Device",
    "query": "label_values(upsCommStatus,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Output Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "0.1*upsHighPrecOutputLoad{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "voltamp",
   "valueName": "current",
   "targets": [
    {
     "expr": "0.01*upsHighPrecOutputCurrent{instance=\"$instance\"}*upsHighPrecOutputVoltage{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "0.1*upsHighPrecBatteryCapacity{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Run Time Remaining",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "upsAdvBatteryRunTimeRemaining{instance=\"$instance\"}/60/100"
    }
   ]
  },
  {
   "title": "Time on Battery",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "m",
   "valueName": "avg",
   "targets": [
    {
     "expr": "upsBasicBatteryTimeOnBattery{instance=\"$instance\"}/60/100"
    }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "0.1*upsHighPrecBatteryTemperature{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "0.1*upsHighPrecInputLineVoltage{instance=\"$instance\"}",
     "legendFormat": "Line Input"
    },
    {
     "expr": "0.1*upsHighPrecOutputVoltage{instance=\"$instance\"}",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "0.1*upsHighPrecInputFrequency{instance=\"$instance\"}",
     "legendFormat": "Input"
    },
    {
     "expr": "0.1*upsHighPrecOutputFrequency{instance=\"$instance\"}",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "0.1*upsHighPrecOutputCurrent{instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "0.1*upsHighPrecBatteryActualVoltage{instance=\"$instance\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Battery Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "upsAdvOutputCurrent{instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Total DC Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "upsHighPrecOutputCurrent{instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  }
 ]
}