{
 "title": "TrueNAS Scale / Overview",
 "tags": [ "truenas" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(uptime,job)" } },
   {
    "name": "host",
    "query": {
     "query": "label_values(uptime{job=\"$job\"},host)"
    }
   },
   {
    "name": "cpu",
    "query": {
     "query": "label_values(cpu_usage{host=\"$host\", job=\"$job\"},cpu)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(disk_io{host=\"$host\", job=\"$job\"},disk)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(interface_io{host=\"$host\", job=\"$job\"},interface)"
    }
   },
   {
    "name": "services",
    "query": {
     "query": "label_values(services_cpu{host=\"$host\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load{host=~\"$host\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "CPU frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "cpu_frequency{host=~\"$host\", cpu=~\"$cpu\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(cpu_temperature{host=~\"$host\", cpu=~\"$cpu\"})",
     "legendFormat": "average_cpu_core_temp"
    },
    {
     "expr": "max(cpu_temperature{host=~\"$host\", cpu=~\"$cpu\"})",
     "legendFormat": "max_cpu_core_temp"
    },
    {
     "expr": "min(cpu_temperature{host=~\"$host\", cpu=~\"$cpu\"})",
     "legendFormat": "min_cpu_core_temp"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_total_bytes{host=~\"$host\"} / 1024 / 1024",
     "legendFormat": "total_memory"
    },
    {
     "expr": "memory_available_bytes{host=~\"$host\"} / 1024 / 1024",
     "legendFormat": "available_memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "interface_io{host=~\"$host\", interface=~\"$interface\"}",
     "legendFormat": "{{interface}} - {{op}}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "processes{host=~\"$host\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Pool State",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zfs_pool{host=~\"$host\"} > 0",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{host=~\"$host\"}",
     "legendFormat": "synced"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_total{host=~\"$host\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "CPU frequency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "cpu_frequency{host=~\"$host\", cpu=~\"$cpu\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "cpu_temperature{host=~\"$host\", cpu=~\"$cpu\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU C-State",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (state) (cpu_idlestate{host=~\"$host\", cpu=~\"$cpu\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "CPU throttling",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "cpu_throttling{host=~\"$host\", cpu=~\"$cpu\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "Interrupts & Context switches",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "interrupts{host=~\"$host\"}",
       "legendFormat": "{{kind}} - interrupt"
      },
      {
       "expr": "context_switches{host=~\"$host\"}",
       "legendFormat": "context switches"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "physical_memory{host=~\"$host\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Swap usage",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "swap{host=~\"$host\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Memory detailed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "memory_available{host=~\"$host\"}",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "memory_committed{host=~\"$host\"}",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "memory_transparent_hugepages{host=~\"$host\"}",
       "legendFormat": "hugepages-{{kind}}"
      },
      {
       "expr": "memory_writeback{host=~\"$host\"}",
       "legendFormat": "writeback-{{kind}}"
      }
     ]
    },
    {
     "title": "Kernel memory allocation",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "memory_kernel{host=~\"$host\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Memory slab",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "memory_slab{host=~\"$host\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "interface_io{host=~\"$host\", interface=~\"$interface\"}",
       "legendFormat": "{{interface}} - {{op}}"
      }
     ]
    },
    {
     "title": "Interface speed",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "interface_speed{host=~\"$host\", interface=~\"$interface\"}",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Interface duplex state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "interface_duplex{host=~\"$host\", interface=~\"$interface\"} > 0",
       "legendFormat": "{{interface}} - {{state}}"
      }
     ]
    },
    {
     "title": "Interface operation state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 15, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "interface_operationstate{host=~\"$host\", interface=~\"$interface\"} > 0",
       "legendFormat": "{{interface}} - {{state}}"
      }
     ]
    },
    {
     "title": "Interface carrier state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "interface_carrierstate{host=~\"$host\", interface=~\"$interface\"} > 0",
       "legendFormat": "{{interface}} - {{state}}"
      }
     ]
    },
    {
     "title": "Interface MTU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "interface_mtu{host=~\"$host\", interface=~\"$interface\"} > 0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Network packets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "interface_packets{host=~\"$host\", interface=~\"$interface\"}",
       "legendFormat": "{{interface}} - {{op}}"
      }
     ]
    },
    {
     "title": "Network errors & drops",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "interface_errors{host=~\"$host\", interface=~\"$interface\"}",
       "legendFormat": "error ({{interface}} - {{op}})"
      },
      {
       "expr": "interface_drops{host=~\"$host\", interface=~\"$interface\"}",
       "legendFormat": "drop ({{interface}} - {{op}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Systemd Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "services_cpu{instance=\"$host\", service=~\"$services\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "services_mem{instance=\"$host\", service=~\"$services\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "Kibits" } },
     "targets": [
      {
       "expr": "services_io{instance=\"$host\", service=~\"$services\", op=\"read\"} * -1",
       "legendFormat": "{{service}} - read"
      },
      {
       "expr": "services_io{instance=\"$host\", service=~\"$services\", op=\"write\"}",
       "legendFormat": "{{service}} - write"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "services_iops{instance=\"$host\", service=~\"$services\"}",
       "legendFormat": "{{service}} - {{op}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processes{host=~\"$host\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Process forks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "processes_forks{host=~\"$host\"}",
       "legendFormat": "forks"
      }
     ]
    }
   ]
  },
  {
   "title": "Uptime + NTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "uptime{host=~\"$host\"}",
       "legendFormat": "synced"
      }
     ]
    },
    {
     "title": "NTP synced",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "clock_synced{host=~\"$host\"}",
       "legendFormat": "synced"
      }
     ]
    },
    {
     "title": "NTP offset",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "clock_offset{host=~\"$host\"}",
       "legendFormat": "offset"
      }
     ]
    },
    {
     "title": "NTP error state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "clock_status{host=~\"$host\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS I/O",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "nfs_io{host=~\"$host\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "NFS net I/O",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "nfs_net{host=~\"$host\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "NFS threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nfs_threads{host=~\"$host\"}",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "NFS readcache",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "nfs_readcache{host=~\"$host\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "NFS RPC",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "nfs_rpc{host=~\"$host\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "NFS proc4",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "nfs_proc4{host=~\"$host\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "NFS proc4ops",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "nfs_proc4ops{host=~\"$host\"}",
       "legendFormat": "{{op}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ZFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "ARC Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "zfs_arc_size{host=~\"$host\", op=~\"arcsz|target\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "L2 Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "zfs_l2_size{host=~\"$host\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "ZFS reads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "zfs_reads{host=~\"$host\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "ZFS cache access",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "zfs_hits{host=~\"$host\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "ARC Size Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "zfs_arc_size_breakdown{host=~\"$host\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "ZFS hash elements",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zfs_hash_elements{host=~\"$host\"}",
       "legendFormat": "hashes - {{op}}"
      }
     ]
    },
    {
     "title": "ZFS important operations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "zfs_important_ops{host=~\"$host\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "ZFS cache hit rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "zfs_hits_rate{host=~\"$host\"}",
       "legendFormat": "{{op}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk - $disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "expr": "disk_io{host=~\"$host\", disk=~\"$disk\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk I/O Ops - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "abs(disk_io_ops{host=~\"$host\", disk=~\"$disk\"})",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk backlog + busy - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "disk_io_backlog{host=~\"$host\", disk=~\"$disk\"}",
       "legendFormat": "backlog"
      },
      {
       "expr": "disk_busy{host=~\"$host\", disk=~\"$disk\"}",
       "legendFormat": "busy"
      }
     ]
    },
    {
     "title": "Disk utilization - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "disk_utilization{host=~\"$host\", disk=~\"$disk\"}",
       "legendFormat": "utilization"
      }
     ]
    },
    {
     "title": "Disk I/O time - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "abs(disk_iotime{host=~\"$host\", disk=~\"$disk\"})",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk await - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "disk_await{host=~\"$host\", disk=~\"$disk\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk avg I/O size - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "abs(disk_io_size{host=~\"$host\", disk=~\"$disk\"})",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk active operations - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "disk_qops{host=~\"$host\", disk=~\"$disk\"}",
       "legendFormat": "value"
      }
     ]
    }
   ]
  }
 ]
}