# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:dX5BblVpRRXZRUyMCqTlaqE3w/WgYi/ey7yWirJcpiXnAyr7nMDNCA==,iv:XkTf2XNjXQDcDr6sMLiYRQaN7U/tRZB8TZWWNyTAI80=,tag:TUnLGJcbuqVAvRxWvOTg4A==,type:str]
sops:
  age:
    - recipient: age1yr8lzheq9nfkyg6ke2yh25ydvm9456p64ukgqu0hxcpvrwyrxy6qgx6luq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRUg2dVVob2VPSUtrZHdu
        YU5GdzRsS2taL29kWVZKYVhsNXFCbHBsQnpRClkzYjIzRk1xeCtDZC9XODAxOVVp
        a1EvSjRTMU9RNksxclBIZFpRZ3JFeTAKLS0tIDM1aW1QOE5lRVlvUWRCd28wS2hW
        Yml1ZitEd1BjN0VvempPZUNaZFNETVEKJDgh2CHoALrTq3Cu1EnpD349n7Mp9WI9
        YqgLPfrGXYGvUN54CRVou3XFv0NGH7BJf3OGWSe6+k5Q9LG6pbMyoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-06T12:47:35Z"
  mac: ENC[AES256_GCM,data:uMa+BklUKRvvzIaEjij1iR1c3+xT6ufkLUc9JAIAv8GqB/9Na5AhEQiFvYfoZxj20pED3EIIxxSKmsENqhxGxodx14Dt9BqyQ4rQ1pNIlwX2ern4ldLWW9+MRUkeX9vyZrfC9GBj1FG+vR25B79frYZ4QYXHq1uSVNqgJ3lDVK0=,iv:ZGLX1ppgHFA/uVLnovcQd+FaPvWjrWWce5f7569j7NQ=,tag:Ed3QJXJpW3sQqqTTg4b2PQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
