# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:iuhTRsQeLLOTGvpZPcZWy+CcRHq9iqIchOBWwpOdm4fYRDTjssCCIg==,iv:JW2x5FY3iVv0/SDEOwFrdGSCe4s2npQMA+zmcntGXf8=,tag:K521yurUOcm3sX1dSOsswg==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid08yWHFWZ1ZPVCtJemZa
        Y2NQL0FRSjltOHNmdzZzNmVrU2EvUjdsWEJVCjcxTDF4aWYzSHEyWmJnTWFadlk5
        a3hKRHBTelg5K3FxbEtrZ1Rhei8zZVkKLS0tIHZ4N2hwY2szd29lbTBsc2toeUFQ
        UW5SeURIWVlEbENjMTlUaU52SUVtWEUKN+H3puaFVO9gw/RyFZKWCznZfrQxFojg
        6t59TG5uRmwMRNIydoBed8go2mKid3UTbV8iMI41/woEL+8gUcqPnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-09T15:03:04Z"
  mac: ENC[AES256_GCM,data:aQqJG1Id2ih8lDZFfA29wK8I6e1SXwcQgaZNodJ14Gqtmwpg35GsjrsZokWmf7cs66DdO4PtQotPtQ80xt3hqUfgMl2/axfLxmGeVQqvIBiYlR5ZF1BMHitArd0B2OD9+9f2k6uyQ8iU8BG3KOp6t0fBg6SMr76QoK18UON20qI=,iv:LBfk7fCY0BOr2kj0yMMQcknAVdyKyiyI4yNZcsB1dWU=,tag:R92qESLl47dgl2XwNqG6hA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
