# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:qhod9GwoU9K8r1d7Mz9pxmrzQlB58+VsPmQx6r4y/b9g7WoBjdXOiw==,iv:qMJ04Bsbo/2tvVOZoJKh4FRkKGaY/PAK71hEAc+9Pq0=,tag:FJq4QugMWHWaCxAxfxpQwQ==,type:str]
sops:
  age:
    - recipient: age1yr8lzheq9nfkyg6ke2yh25ydvm9456p64ukgqu0hxcpvrwyrxy6qgx6luq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGU0VRbjdVcWU0bVo3WnNa
        OWxJZ1NPRGRZMmJIR0E1SThPak5TR0pKSUFNCnRxb1g5VTFJdGYzUDdVTmt3VGZ0
        Z0w5ZXlKMkNrakFocGVGdU8vc09JL1kKLS0tIFAybXdWSjFxY2JteW1LRGs4R3ph
        K0JvbFlmRjZWTUY2ZTExYjFvQXpCdUUKiB5jCzEjWXWoMPyC+yXDxzCPRQgIMsn4
        biyD5nRJuWMausJ27QRexX3PVckBqW5n8e59NvSbBRrA81LW5/VqjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-07T17:13:55Z"
  mac: ENC[AES256_GCM,data:EwRJ6etYXPjBxUIse7aWZutWqgij/2t/Ss/XhfnO94sudb7tzO1CE+qwTqYvttEczd1NnB1cqbyR2ch2sQVtb8VxkqJv+nssEDz1f/keADW/kjdWzsaQTQnHzNsTZVMA9EvxVhX4sr66UmgK3y00hRrhvs49B/RI3yCxbrj1Ck0=,iv:a5QigJeF1jpgL/GJsdwQxYJchnRckUDrtAYi2jwL/g8=,tag:lZiaQR5YbzDgL08EkDYu8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
