---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &app postgres-v17-immich
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17-0.5.3@sha256:48bdf65dfd22111ccacc345d0bf4f1b944a4da88c9202f0448a695240a47c555

  instances: 3

  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi
    storageClass: rook-ceph-block

  walStorage:
    size: 8Gi
    storageClass: rook-ceph-block

  enableSuperuserAccess: true

  superuserSecret:
    name: cloudnative-pg-secret

  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      timezone: ${TIMEZONE}
      max_connections: "600"
      shared_buffers: 512MB
    shared_preload_libraries:
      - "vchord.so"

  resources:
    requests:
      cpu: 500m
    limits:
      memory: 4Gi

  # Spread the pods evenly across nodes
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: *app

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters: &parameters
        barmanObjectName: minio
        serverName: &currentCluster postgres-v17-immich-v1

  bootstrap:
    # Use this to recover a net-new cluster from a backup
    recovery:
      source: &previousCluster postgres-v18-immich-v0

  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: *previousCluster
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters: *parameters