---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.10.16.130:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.10.16.130"
  - "k8s.internal"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-clus01-cp01"
    ipAddress: "10.10.16.131"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/27c006c61185fc860f848e16cad265db959a24af02fe04a2a6c92965c34c697b
    controlPlane: true
    networkInterfaces:
      - interface: "eth0"
        dhcp: false
        vlans:
          - vlanId: 16
            addresses:
              - "10.10.16.131/24"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.10.16.1"
            vip:
              ip: "10.10.16.130"

  - hostname: "talos-clus01-cp02"
    ipAddress: "10.10.16.132"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/27c006c61185fc860f848e16cad265db959a24af02fe04a2a6c92965c34c697b
    controlPlane: true
    networkInterfaces:
      - interface: "eth0"
        dhcp: false
        vlans:
          - vlanId: 16
            addresses:
              - "10.10.16.132/24"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.10.16.1"
            vip:
              ip: "10.10.16.130"

  - hostname: "talos-clus01-cp03"
    ipAddress: "10.10.16.133"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/27c006c61185fc860f848e16cad265db959a24af02fe04a2a6c92965c34c697b
    controlPlane: true
    networkInterfaces:
      - interface: "eth0"
        dhcp: false
        vlans:
          - vlanId: 16
            addresses:
              - "10.10.16.133/24"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.10.16.1"
            vip:
              ip: "10.10.16.130"

  - hostname: "talos-clus01-wk01"
    ipAddress: "10.10.16.141"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/bef9b5ce3c20cc34a10d3a9e0efb99c41043f5422f7aba45838d6913621968d7
    controlPlane: false
    networkInterfaces:
      - interface: "eth0"
        dhcp: false
        vlans:
          - vlanId: 16
            addresses:
              - "10.10.16.141/24"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.10.16.1"

  - hostname: "talos-clus01-wk02"
    ipAddress: "10.10.16.142"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/bef9b5ce3c20cc34a10d3a9e0efb99c41043f5422f7aba45838d6913621968d7
    controlPlane: false
    networkInterfaces:
      - interface: "eth0"
        dhcp: false
        vlans:
          - vlanId: 16
            addresses:
              - "10.10.16.142/24"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.10.16.1"

  - hostname: "talos-clus01-wk03"
    ipAddress: "10.10.16.143"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/bef9b5ce3c20cc34a10d3a9e0efb99c41043f5422f7aba45838d6913621968d7
    controlPlane: false
    networkInterfaces:
      - interface: "eth0"
        dhcp: false
        vlans:
          - vlanId: 16
            addresses:
              - "10.10.16.143/24"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.10.16.1"

  - hostname: "talos-clus01-wk04"
    ipAddress: "10.10.16.144"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/402134c742e0d63a25f5c42467e86eae50468dfb48c0be2a82e73f789b42ae63
    controlPlane: false
    networkInterfaces:
      - interface: "eth0"
        dhcp: false
        vlans:
          - vlanId: 16
            addresses:
              - "10.10.16.144/24"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.10.16.1"

  - hostname: "talos-clus01-wk05"
    ipAddress: "10.10.16.145"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/402134c742e0d63a25f5c42467e86eae50468dfb48c0be2a82e73f789b42ae63
    controlPlane: false
    networkInterfaces:
      - interface: "eth0"
        dhcp: false
        vlans:
          - vlanId: 16
            addresses:
              - "10.10.16.145/24"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.10.16.1"

  - hostname: "talos-clus01-wk06"
    ipAddress: "10.10.16.146"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/402134c742e0d63a25f5c42467e86eae50468dfb48c0be2a82e73f789b42ae63
    controlPlane: false
    networkInterfaces:
      - interface: "eth0"
        dhcp: false
        vlans:
          - vlanId: 16
            addresses:
              - "10.10.16.146/24"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.10.16.1"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

