---
originRequest:
  originServerName: "external.${PUBLIC_DOMAIN}"

ingress:
  - hostname: "${PUBLIC_DOMAIN}"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.${PUBLIC_DOMAIN}"
    service: *svc
  - service: http_status:404
