---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pgadmin
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      pgadmin:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: dpage/pgadmin4
              tag: 9.9@sha256:5d9624a93634d1c5e595619cc57b1d330758120d1baf445fa97300c0c1fc3c0a
            env:
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: pgadmin-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 80
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 500Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 5050 # pgadmin user
        runAsGroup: 5050 # pgadmin group
        fsGroup: 5050
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        ports:
          http:
            port: *port

    serviceMonitor:
      app:
        endpoints:
          - port: http

    route:
      app:
        annotations:
          # Homepage Automatic Service Discovery
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "PGAdmin"
          gethomepage.dev/description: "PostgreSQL Database Management Tool"
          gethomepage.dev/icon: "pgadmin"
          gethomepage.dev/group: "Database"
        hostnames: ["{{ .Release.Name }}.${PUBLIC_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        enabled: true
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /var/lib/pgadmin

      server-json:
        enabled: true
        type: configMap
        name: pgadmin-servers
        globalMounts:
          - path: /pgadmin4/servers.json
            subPath: servers.json

