---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: cloudnative-pg-secret
    template:
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        AWS_ACCESS_KEY_ID: "{{ .MINIO_ROOT_USER }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MINIO_ROOT_PASSWORD }}"
  data:
    - secretKey: POSTGRES_SUPER_USER
      remoteRef:
        key: 6d34d21b-666e-4ea2-9aef-b37e01138762
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: b360e01d-86e8-4cee-9096-b37e011397c9
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: 811a75d1-9889-43c6-b423-b37e0113ec6d
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: a075cdd4-ff6e-48db-9ebe-b37e0113fde4