---
# yaml-language-server: $schema=https://raw.githubusercontent.com/rook/rook/v1.12/deploy/examples/crds.yaml#/CephCluster
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: external-cluster
  namespace: rook-ceph
spec:
  external:
    enable: true
  dataDirHostPath: /var/lib/rook
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.3 # needs to match the version in proxmox