---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-csi-rbd-provisioner
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: rook-csi-rbd-provisioner
    template:
      type: kubernetes.io/rook # necessary to have the secret formatted for rook
      data:
        userID: k8s-rbd-provisioner
        userKey: "{{ .CEPH_K8S_RBD_PROVISIONER }}"
  data:
    - secretKey: CEPH_K8S_RBD_PROVISIONER
      remoteRef:
        key: 8e2a683d-3cff-4439-810b-b3770032c705
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-csi-rbd-node
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: rook-csi-rbd-node
    template:
      type: kubernetes.io/rook # necessary to have the secret formatted for rook
      data:
        userID: k8s-rbd-node
        userKey: "{{ .CEPH_K8S_RBD_NODE }}"
  data:
    - secretKey: CEPH_K8S_RBD_NODE
      remoteRef:
        key: a009bdc2-b13a-4a32-aa56-b3770032dc04
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-operator-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: rook-ceph-operator-creds
    template:
      data:
        userID: client.healthchecker
        userKey: "{{ .CEPH_CLIENT_HEALTHCHECKER }}"
  data:
    - secretKey: CEPH_CLIENT_HEALTHCHECKER
      remoteRef:
        key: a92d8108-2e14-407b-bdbf-b3770123f870
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-mon
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: rook-ceph-mon
    template:
      data:
        fsid: "{{ .CEPH_FSID }}"
        admin-secret: "{{ .CEPH_ADMIN_SECRET }}"
        mon-secret: "{{ .CEPH_MON_SECRET }}"
  data:
    - secretKey: CEPH_FSID
      remoteRef:
        key: 333d1da2-1eae-4590-b716-b3770119ad45
    - secretKey: CEPH_ADMIN_SECRET
      remoteRef:
        key: f2370311-f23b-4e67-82cd-b3770119da1a
    - secretKey: CEPH_MON_SECRET
      remoteRef:
        key: c62d465f-8d0d-4047-84d0-b3770119fb57