---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-csi-rbd-provisioner
  namespace: storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: rook-csi-rbd-provisioner
    template:
      type: Opaque
      data:
        userID: k8s-rbd-provisioner
        userKey: "{{ .CEPH_K8S_RBD_PROVISIONER }}"
  data:
    - secretKey: CEPH_K8S_RBD_PROVISIONER
      remoteRef:
        key: 8e2a683d-3cff-4439-810b-b3770032c705
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-csi-rbd-node
  namespace: storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: rook-csi-rbd-node
    template:
      type: Opaque
      data:
        userID: k8s-rbd-node
        userKey: "{{ .CEPH_K8S_RBD_NODE }}"
  data:
    - secretKey: CEPH_K8S_RBD_NODE
      remoteRef:
        key: a009bdc2-b13a-4a32-aa56-b3770032dc04
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-external-cluster-details
  namespace: storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: rook-ceph-external-cluster-details
    template:
      type: Opaque
  data:
    - secretKey: CEPH_CLUSTER_DETAILS
      remoteRef:
        key: 0f8808dc-e91b-433b-b6d3-b377003859bc
