apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-smoke
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: rook-ceph-rbd-external-cluster
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: rbd-volume
          mountPath: /mnt
  volumes:
    - name: rbd-volume
      persistentVolumeClaim:
        claimName: rbd-smoke