---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: excalidraw
spec:
  chartRef:
    kind: OCIRepository
    name: excalidraw
  interval: 1h
  dependsOn:
    - name: cloudflare-tunnel
      namespace: network
  values:
    controllers:
      excalidraw:
        strategy: RollingUpdate

        initContainers:
          perms:
            image:
              repository: busybox
              tag: "1.37"
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: false
              capabilities:
                add: ["CHOWN"]
            command: ["sh", "-c"]
            args:
              - >
                mkdir -p /etc/nginx &&
                chown -R 101:101 /etc/nginx &&
                chmod -R 775 /etc/nginx

        containers:
          app:
            image:
              repository: excalidraw/excalidraw
              tag: latest@sha256:ddcc677525fd796fa871bdf2b2ffae8f3bc311e19037ab29abfc735b7dc415f7
            env:
              TZ: "America/Chicago"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              runAsNonRoot: true
              # nginx user
              runAsUser: 101
              runAsGroup: 101
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 200Mi

    defaultPodOptions:
      securityContext:
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        ports:
          http:
            port: *port

    serviceMonitor:
      app:
        endpoints:
          - port: http

    route:
      app:
        annotations:
          # Homepage Automatic Service Discovery
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Excalidraw"
          gethomepage.dev/description: "whiteboard tool"
          gethomepage.dev/icon: "sh-excalidraw"
          gethomepage.dev/group: "Documentation"
        hostnames: ["{{ .Release.Name }}.${PUBLIC_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
        nginx-cache:
          type: emptyDir
          medium: Memory
          sizeLimit: 128Mi
          globalMounts:
            - path: /var/cache/nginx
        nginx-run:
          type: emptyDir
          medium: Memory
          sizeLimit: 64Mi
          globalMounts:
            - path: /var/run
