---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dragonfly-operator
spec:
  chartRef:
    kind: OCIRepository
    name: dragonfly
  interval: 30m
  values:
    controllers:
      dragonfly-operator:
        annotations:
          reloader.stakater.com/auto: "true"

        strategy: RollingUpdate

        containers:
          app:
            image:
              repository: ghcr.io/dragonflydb/operator
              tag: v1.3.0@sha256:ee0daee0bb11185c984bbea92b0e8cc17a06ae4cd246e0d311c814f6948fd27e

            command: ["/manager"]

            args:
              - "--health-probe-bind-address=:8081"
              - "--metrics-bind-address=127.0.0.1:8080"
              - "--leader-elect"

            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                  timeoutSeconds: 1
                  failureThreshold: 3

              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3

            resources:
              requests:
                cpu: 5m
                memory: 64Mi
              limits:
                cpu: 500m
                memory: 256Mi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
          metrics:
            port: 8080

    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    grafanaDashboard:
      enabled: true

    serviceAccount:
      dragonfly-operator: {}
