---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app atuin
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      atuin:

        containers:
          app:
            image:
              repository: ghcr.io/atuinsh/atuin
              tag: v18.10.0@sha256:4a29feda6f352581ece849807445fe1f50f2074b4643b7bfe62b27e23705b068
            env:
              ATUIN_HOST: "0.0.0.0"
              ATUIN_PORT: &port 80
              ATUIN_METRICS__ENABLE: true
              ATUIN_METRICS__HOST: 0.0.0.0
              ATUIN_METRICS__PORT: &metricsPort 8081
              ATUIN_OPEN_REGISTRATION: "true"
              ATUIN_DB_URI: sqlite:///config/atuin.db
              TZ: ${TIMEZONE}
            command:
              - atuin
              - server
              - start
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        ports:
          http:
            port: *port

    serviceMonitor:
      app:
        endpoints:
          - port: http

    route:
      app:
        annotations:
          # Homepage Automatic Service Discovery
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Atuin"
          gethomepage.dev/description: "magical shell history"
          gethomepage.dev/icon: "sh-atuin"
          gethomepage.dev/group: "Default"
        hostnames: ["{{ .Release.Name }}.${PUBLIC_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
