---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter-apc-ups
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    fullnameOverride: *app
    image:
      repository: quay.io/prometheus/snmp-exporter
      tag: main@sha256:faac41c7747a4620612e1f3b0a984a60a99675452c1c859d0346ee1f7d7ce0a8
    extraArgs: ["--config.file=/config/snmp.yaml"]
    extraConfigmapMounts:
      - name: &config apc-ups-snmp-configmap
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: *config
        readOnly: true
        defaultMode: 420
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
    serviceMonitor:
      enabled: true
      params:
        - name: apc-ups
          module: [apcups]
          target: apc-ups.internal
          interval: 120s
          auth: ["public_v1"]
      path: /snmp
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels:
            - __param_target
          targetLabel: instance