---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      identityURL: https://vault.bitwarden.com/identity
      bitwardenServerSDKURL: https://bitwarden-sdk-server.security.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
            namespace: &namespace security
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: *namespace
        key: ca.crt
      organizationID: ${BITWARDEN_ORGANIZATION_ID}
      projectID: ${BITWARDEN_PROJECT_ID}