---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name bitwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: *name
  target:
    name: *name
    template:
      data:
        token: ${BITWARDEN_ACCESS_TOKEN}
  data:
    - secretKey: key
      remoteRef:
        key: bitwarden_machine_key