# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-secrets
stringData:
  BITWARDEN_ORGANIZATION_ID: ENC[AES256_GCM,data:dOEiuF7ABuUr9j6NUy3TC2jHhCIa2Edt3gNS463qsyoMNfWq,iv:HZSHmHMF9BXHczsxkpJqZPfKH5RrIEWwtGlzc3J4yg0=,tag:oPdrCQURi6YlZ7EI5GsRqg==,type:str]
  BITWARDEN_PROJECT_ID: ENC[AES256_GCM,data:w77+2ZX2ncks9zO+HFfk0uDPlL8HGDntunY/O6hInYOf/W1I,iv:flCOieCPlXkNogj2I0t1drtPg1HvDzkYvHFhAz5WcBY=,tag:fnIb8cPs8cvks8g/7ppXrQ==,type:str]
  BITWARDEN_ACCESS_TOKEN: ENC[AES256_GCM,data:zh9gwtwdvFBH+FJSVRqk3mtg8t+zoDNCb59uxn5EjlUjtqRzYYl0anZQ0ucFEdy/R43CXJYEVIZarppS4RtU+Fteu/P6wiswj6slz+0tQ8Txi66tumI1oWz+nSI1tA==,iv:WqWOaGRdO1N9ObHpwXunLG3tLZUzPJcol9GMWO7SPMM=,tag:wr4NzMy/hrDC/OgzEzf4gQ==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3akYxcEpVOHY2dVRxVnpn
        eTl0WVZZd2VWNGdrQ2tNVmd3SnRXZHFzR0VJCndKdmd0dm1RNUt2NDFVYUFUSkN1
        cU9WSnZkWis4UHFXY0o2Rk9NZEptRk0KLS0tIE9nV0QvWndTSFkzUVJaUTVKcndI
        UlZnU2R6ZnAyR0xGTjZsY1V0d2pjT2sKd6QjKlLpAfJf5EcNjHVcuQDaYxHOrWRJ
        MNd69cRNuHqNBK6WnfIUZMM5MmM9Hv25OOXSU9zgRWFTHma2V868Zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-14T15:27:35Z"
  mac: ENC[AES256_GCM,data:wsEdJe/nnM0ydqPDcnJrPyPaelffUdLLCwc2R3bS9DY6bNZfuMwphNcx0fOpHqxNXyRc80nHz3piA55oyDUAu4va1mZjgT+paouhYPaBdB1q73Z1+qyn7js3h7VW5XYY15ylpel1iQEbX+DI2M7M7IxQjCvUbfBgj1uXIFbl0Dg=,iv:5AEsaHCDQj2z+Ys6KGjsKlLSA2n0PL9YJkdAPg15Eu8=,tag:rmDrIZ89zRTO4Go54ciz7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
