# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-access-token
stringData:
  token: ENC[AES256_GCM,data:U1IpZOJqmn2ZgP3D0LNDWWqkGiG7ftj0TVldFTWbC8aRpg3U6j4bRyOw2s9wvVsRgPKKfrCQHbNTckK2AGMgokG//r+Q7XyxPTNR1c7g7wpCzVr+tgV4YFtkh82fEQ==,iv:h50TfvEoqETU9aSWFZHytr6FN9H2cLF0l4HpeTQP+kk=,tag:ZdOWcSQwXFniubl1cfgIZg==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3akYxcEpVOHY2dVRxVnpn
        eTl0WVZZd2VWNGdrQ2tNVmd3SnRXZHFzR0VJCndKdmd0dm1RNUt2NDFVYUFUSkN1
        cU9WSnZkWis4UHFXY0o2Rk9NZEptRk0KLS0tIE9nV0QvWndTSFkzUVJaUTVKcndI
        UlZnU2R6ZnAyR0xGTjZsY1V0d2pjT2sKd6QjKlLpAfJf5EcNjHVcuQDaYxHOrWRJ
        MNd69cRNuHqNBK6WnfIUZMM5MmM9Hv25OOXSU9zgRWFTHma2V868Zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-14T21:20:33Z"
  mac: ENC[AES256_GCM,data:LVRavSEvR3KDJZkz8Tn2+5BXw3//7bp4wLGMDh8xgXdSUQ+t3UKyZPg29yRdVBJL6woQ2rty0fWLPm2AP7uSaIonxJOeYSXhBww7Usd9cNdB2M5xxQoEbw3C9BDMaKyOLN/s4iA15KJZIeE+OkKa3WsllOUUO1cm87ECPVZ5TJo=,iv:NBN7rZaPe9UrnmSW7RminA1iV6hIeOpT+NZl7DhgsLA=,tag:Z/iDhlFgZ4bEioaE1ts7zw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
