apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:2dpG8EjMI66W8cw=,iv:OHDiZxeqHwJco6lNYwL/pNbbTcteFic9DzI9ZVhjdMU=,tag:JUt++wvsFjvQ/xWEEUyehQ==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWXh1T2VQN0s3Y2g1azhF
        d0VieG9zcDhKY3lrNUxvQWJIcXZNRnVVbmpZClRCUUN4ZlZHRXlXNzN0c1JsVXFw
        Mm0xVmJOekFzY2QzaDAwRlk0K0hDL28KLS0tIHRaenlBZENwRVBzblVRaWY1RE1w
        dlZpT0xWUzNIbTJ4VUV5b1lLcFdKdGsKNBxNyrp4C6f85s8QSUkw2yyx6Zw9E+x/
        xjfcayENptdI9ePRdsRQk/yEqOympeSA/BPBrDtW+781s0upxtYcRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-09T15:03:04Z"
  mac: ENC[AES256_GCM,data:8ATX0CYqIm5/NXcRoIPXeSlnemzTvTSQRMIdEUmOY2h76VP3xbdA/IEafYubatkUzzTc+WKAkchkhKO5YYS/NKkWw5H7AKEthRrNzXwF637q6V7TlsACyD0vj99TT9hVTUGuYb0gA7KL6EQzO2gbeZZD7r9n9v8nQFfAMFbjKAs=,iv:J6yDlG//uxmhrlo49LP8TCl/e5OcttyZU/Ngp8v4h24=,tag:dQK/V7Ipx7wfcwEp4Bs8jw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
