apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:nNn7X49BTlvo9kE=,iv:U7blGM4Ptm6KBR1uXxINxMidsJH7+WNFwS8eZbSThn0=,tag:ZbjLSnPUsZy5Bea6QaD3XA==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMTVmdTkvbFRGdmczV3ZX
        MW9CY0ljQkhNaDhqV1llWHBqQ3M1N3lkOHhrClRVbUN6T3kvRU94MXNrSkUzc29x
        M0MxbHBhS25yYUphdlhvK0ZyOHVHNVkKLS0tIDY0b3JOa2lIZUZVeGRBZWVyZmFj
        a2s4am5xNml0UlFXQUFIeG1GNUcwZEEKSJQayRQFS1/c19v5XCWKJMToqYep/1XN
        nF5ZzsNIROOnpodlTMrEqgQEuHkSYx3CiFsTrWlBGul60ZxZ+uTSeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-09T21:43:09Z"
  mac: ENC[AES256_GCM,data:9+7ymI7eRC7mbrpXpoylxNAeGDA2aOqXM5d3ik3suu00+hdhsn0L6ktSkv98ULoTn41Z/odb8Upbs6suTT5y4OGmCxsBm9LlIzh4MXIASrLqlqqc992liMecTwUbW8y7brwJOHtkRqIj+QUePioEKhdglrqHozqWkGyyZsjHKME=,iv:lGjcjKoZMOHo8lCTQcNWP02YyM7CavpWBigKvta8RUE=,tag:qMtViUEQs997KSMIpjvVhQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
