apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  PUBLIC_DOMAIN: ENC[AES256_GCM,data:8KOi4ANhrNP3x/0=,iv:qJ7VGwBKaHzsEzOQCFksoW+u0JZig2upJ391RFvls0A=,tag:QZBxPTYvoBmdvpcGqYyu2w==,type:str]
sops:
  age:
    - recipient: age10pcwu0f2vyathrgzppd2r6cvu0utu7fps233f2pvjps7f3t744rsrjzaz4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMTVmdTkvbFRGdmczV3ZX
        MW9CY0ljQkhNaDhqV1llWHBqQ3M1N3lkOHhrClRVbUN6T3kvRU94MXNrSkUzc29x
        M0MxbHBhS25yYUphdlhvK0ZyOHVHNVkKLS0tIDY0b3JOa2lIZUZVeGRBZWVyZmFj
        a2s4am5xNml0UlFXQUFIeG1GNUcwZEEKSJQayRQFS1/c19v5XCWKJMToqYep/1XN
        nF5ZzsNIROOnpodlTMrEqgQEuHkSYx3CiFsTrWlBGul60ZxZ+uTSeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-14T20:48:00Z"
  mac: ENC[AES256_GCM,data:Ef3gCBA6LpXDy2/lcWGl+q/NCTj1Qpvn5lob+++zhK8agJGSaKSUKtgFCdUP9eaeEctVL2wYpx3ZuByEh2DvsyXc7wUi0dNmkLTCNK6zsmAOmMzEniGZT3HhoMjurJIF96tibIEh7S1oI8aGqcG1Lai6f+JKvNzwtAnj3Q9TnCw=,iv:aoZLi8xHGnItVf+ItTbP9q+g2gAPvXC3ZXlMg/hoEkg=,tag:IeJEwABPL8zKUYzGvB7KnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
