apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:bX4froMB3ntROV5yfaYCBivbfcVFD5KV5dNx5MhnXGibER127aGk8U2d9neCsOzBAzreVHc7+O6KuwndSRepbSQ43Tr9T+c+DzA=,iv:wlZSYR6YlFvY4EhHqoT22KUP80e5BQ6rPzdobNA3Yzg=,tag:R9rsitfZPPepndDdVw1IHw==,type:str]
sops:
  age:
    - recipient: age1yr8lzheq9nfkyg6ke2yh25ydvm9456p64ukgqu0hxcpvrwyrxy6qgx6luq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIR3pyUVlSVjJRTmErSEhU
        eHpCZFN1NFJRS3RvaEhOTnRhZTBLUmJjVENFCnRSTklHTnRJd1JmdnJqWkZFeklZ
        Qk10SzhFYXVYdzVOcHFLbFRzbXp4dGcKLS0tIFVmdTBaMDhhQjFhM3B1K054MXRB
        WVdZQzJJSVEyZzFHdmNERmhmWHZRUjQKMie27U8vJRlhUdClT7UZlngJvFafKKGf
        lGZWJIs6NMhSIU+20MBnDDlQwBRruDC/AqhrExx+nvRxzJi050pbVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-07T12:16:18Z"
  mac: ENC[AES256_GCM,data:/RtiVLOMNCe5IMBAC/hAliXbGLfHVAD2iEfDblNQtmSEyMh2RIBxoSeEt6Z+HZcYPM4sy6P+Pq1UfdOElbHQMLM5reS/DOxfwExXrLyRZbeBIQMk+KChqLtZgs3YxW7UxvCOXrrqaphAGRQ3L9lNcBMA/OCdMXQcmX9vwT752LI=,iv:+D00OLOdrLQu972+6IpmDwYI/bOR40ebjzN2lDIRE7E=,tag:9Z/DUGO7vA5DP+KnoLUOcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
